version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9393:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
