global:
  scrape_interval: 5s  # Coleta métricas a cada 5 segundos

scrape_configs:
  - job_name: "node-api"
    static_configs:
      - targets: ["host.docker.internal:3000"] # Aponta para seu servidor Node.js
